-- Disable RLS for development (no auth yet)
-- Re-enable with proper policies when auth is added

ALTER TABLE organizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE team_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE initiatives DISABLE ROW LEVEL SECURITY;
ALTER TABLE tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE action_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE effort_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE stakeholders DISABLE ROW LEVEL SECURITY;
ALTER TABLE initiative_stakeholders DISABLE ROW LEVEL SECURITY;
ALTER TABLE application_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE field_options DISABLE ROW LEVEL SECURITY;
ALTER TABLE capacity_thresholds DISABLE ROW LEVEL SECURITY;
ALTER TABLE workload_calculator_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE id_counters DISABLE ROW LEVEL SECURITY;
ALTER TABLE pipeline_items DISABLE ROW LEVEL SECURITY;
